### ISSUE TITLE
Hold smile animation longer

### ISSUE THREAD

**Issue by krpeacock** [lanebreach/web_app#18]

**Comment by lukemccrae** [comment]
I think I can use vid.currentTime to pause/unpause the .gif to make the page stay up longer. Or I can just add more frames to the gif itself. Do you have a preference?

**Comment by krpeacock** [comment]
From what I can tell, the proper way to do it now would be to use react
suspense to delay rendering while the gif loads.

Extending the screen duration another second wouldn't hurt anyway.

Kyle Peacock

**Comment by krpeacock** [comment]
Basically, there are two issues:  

1. The screen is hardcoded for a fixed time, so it can close before the gif finishes
2. We'd like to leave the completed gif up for longer after it runs

For the first issue, we could add an [onload](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XUL/Attribute/image.onload) attribute to the gif that would start the success screen once it's loaded.

There are probably is also a way that we could preload the gif in the background so that it's available on the browser to make it snappier in the moment. Not a great pattern for data optimization generally, but since we'd only be doing it for an asset it's worth.

Then, assuming we've got that timing solved, the easier thing to do is to add another second to the timeout to leave the screen up longer

**Comment by krpeacock** [comment]
This is now merged
